it:
  code: ita
  name: italiano
  t:
    active_lang: lingua attiva
    cookiebar_accept: Accetto
    cookiebar_msg: Questo sito utilizza cookie tecnici, analytics e di terze parti. Proseguendo nella navigazione accetti l’utilizzo dei cookie.
    cookiebar_privacy_policy: Privacy policy
    follow_us: seguici su
    footer_address: Indirizzo
    footer_address_sub: ''
    footer_contacts: Contatti
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy policy
    footer_link_toc: note legali
    lang_on_site: sito in italiano
    navigation_menu_label: Menu di navigazione
    navigation_menu_esc: esci dalla navigazione
    scrolltop_label: torna all'inizio dei contenuti
    search_form_label: cerca
    search_form_off: disattiva il form di ricerca
    search_form_on: attiva il form di ricerca
    search_form_start: avvia la ricerca
    site_subtitle: Il mio favoloso sottotitolo
    site_title: Il mio favoloso titolo del sito
    share_msg: condividi
    skiplink_goto_content: vai ai contenuti
    skiplink_goto_navigation: vai alla navigazione del sito
en:
  code: eng
  name: english
  t:
    active_lang: current language
    cookiebar_accept: Accept
    cookiebar_msg: We are using cookies to provide statistics that help us give you the best experience of our site. By continuing to use the site you are agreeing to our use of cookies.
    cookiebar_privacy_policy: Privacy policy
    follow_us: follow us
    footer_address: Address
    footer_address_sub: ''
    footer_contacts: Contacts
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy policy
    footer_link_toc: terms and conditions
    lang_on_site: website in english
    navigation_menu_label: Navigation menu
    navigation_menu_esc: exit navigation
    scrolltop_label: back to contents
    search_form_label: Search
    search_form_off: exit search form
    search_form_on: enter search form
    search_form_start: start searching
    site_subtitle: My awesome subtitle
    site_title: My awesome site title
    share_msg: share
    skiplinks_goto_content: go to content
    skiplinks_goto_navigation: go to site navigation
