<?xml version="1.0" encoding="UTF-8"?> 
<wsdl:definitions targetNamespace="http://sogei.it/ANPR/E004AnprService"
				  xmlns:tns="http://sogei.it/ANPR/E004AnprService" 
				  xmlns:schema="http://sogei.it/ANPR/E000Vocabolario" 
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
				  xmlns:xsd="http://www.w3.org/2001/XMLSchema">  
	
	<wsdl:types> 
		<xsd:schema targetNamespace="http://sogei.it/ANPR/E004AnprService">    
			<xsd:import namespace="http://sogei.it/ANPR/E000Vocabolario" schemaLocation="E000Vocabolario.xsd" />  
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="RichiestaE004">
		<wsdl:part name="request" element="schema:RichiestaE004"/>  
	</wsdl:message>
	<wsdl:message name="RispostaE004">  
		<wsdl:part name="response" element="schema:RispostaE004"/>  
	</wsdl:message>	
	
	<wsdl:portType name="AnprPortTypeE004">  
		<wsdl:operation name="download_file">    
			<wsdl:input   message="tns:RichiestaE004"/>    
			<wsdl:output  message="tns:RispostaE004" />  
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="AnprBindingE004" type="tns:AnprPortTypeE004">    
		<wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>    
		<wsdl:operation name="download_file">      
			<wsdlsoap:operation soapAction=""/>      
			<wsdl:input>        
				<wsdlsoap:body use="literal"/>      
			</wsdl:input>      
			<wsdl:output>        
				<wsdlsoap:body use="literal"/>      
			</wsdl:output>   
		</wsdl:operation>  
		 
	</wsdl:binding>  
	
	<wsdl:service name="AnprServiceE004">    
		<wsdl:port binding="tns:AnprBindingE004" name="AnprServicePortE004">      
			<wsdlsoap:address location="http://www.sogei.it/Interno/ANPR/AnprServiceE004"/>    
		</wsdl:port>  
	</wsdl:service>
	
</wsdl:definitions>